"""Semantic Mapping Pipeline (Project 2).

This module complements the ROS launch defined in `launch_slam_rtmap.py` by providing a
conceptual semantic mapping pipeline that consumes the RealSense RGB/Depth streams and
optionally YOLO/SAM detections. The `_semantic_segmentation` and
`build_semantic_map_step()` methods demonstrate how AI-driven labels can be fused with the
3D map generated by RTAB-Map in real time.

The code is simulation-friendly: when AI detections are not provided it falls back to a
mock model, yet the API matches what a real system would expose so it can be swapped for
production components.
"""

from __future__ import annotations

import json
import os
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Tuple

import numpy as np
import open3d as o3d

# Optional OpenCV support for standalone demos or debugging visualisations.
try:  # pragma: no cover - OpenCV may be unavailable in headless environments
    import cv2
except ImportError:  # pragma: no cover
    cv2 = None  # type: ignore

try:  # pragma: no cover - ROS 2 may not be installed in all dev environments
    import rclpy
    from rclpy.node import Node
    from sensor_msgs.msg import CameraInfo, Image
    from std_msgs.msg import String
except ImportError as exc:  # pragma: no cover
    rclpy = None  # type: ignore
    Node = object  # type: ignore
    ROS_IMPORT_ERROR = exc
else:  # pragma: no cover
    ROS_IMPORT_ERROR = None

try:  # pragma: no cover - cv_bridge is ROS-specific
    from cv_bridge import CvBridge
except ImportError:  # pragma: no cover
    CvBridge = None  # type: ignore


@dataclass
class Detection2D:
    """Simple container describing a 2D detection rectangle."""

    label: str
    confidence: float
    bbox: Tuple[int, int, int, int]


@dataclass
class SemanticMapConfig:
    """Runtime configuration aligned with `launch_slam_rtmap.py`."""

    rgb_topic: str = os.getenv("SEMANTIC_RGB_TOPIC", "/camera/camera/color/image_raw")
    depth_topic: str = os.getenv("SEMANTIC_DEPTH_TOPIC", "/camera/camera/aligned_depth_to_color/image_raw")
    camera_info_topic: str = os.getenv("SEMANTIC_CAMERA_INFO_TOPIC", "/camera/camera/color/camera_info")
    detection_topic: str = os.getenv("SEMANTIC_DETECTION_TOPIC", "/yolo/detections")
    status_topic: str = os.getenv("SEMANTIC_STATUS_TOPIC", "/semantic_map/status")
    publish_visualisation: bool = bool(int(os.getenv("SEMANTIC_DISPLAY", "0")))
    classes: Tuple[str, ...] = (
        "chair",
        "table",
        "person",
        "monitor",
        "backpack",
        "door",
    )


class RTABMapAccumulator:
    """Conceptual representation of RTAB-Map's global map store."""

    def __init__(self) -> None:
        self._map = o3d.geometry.PointCloud()

    @property
    def map(self) -> o3d.geometry.PointCloud:
        return self._map

    def add_segment(self, segment: o3d.geometry.PointCloud) -> int:
        self._map += segment
        return len(self._map.points)


class SemanticMappingPipeline:
    """Project 2 semantic mapping pipeline feeding into RTAB-Map (Project 5)."""

    def __init__(self, classes: Iterable[str], camera_params: Optional[Dict[str, float]] = None) -> None:
        self.classes = list(classes)
        self.camera_params = camera_params or {
            "fx": 614.0,
            "fy": 614.0,
            "cx": 320.0,
            "cy": 240.0,
            "scale": 1000.0,  # Depth scale from mm to metres.
        }
        self.mapper = RTABMapAccumulator()
        self.latest_summary: Optional[Dict[str, Any]] = None

    # ------------------------------------------------------------------
    # --- Core Semantic Mapping Methods (Project 2) --------------------
    # ------------------------------------------------------------------
    def _semantic_segmentation(
        self,
        rgb_frame: np.ndarray,
        detection_payload: Optional[str] = None,
    ) -> List[Detection2D]:
        """Simulate AI-based segmentation (YOLO/SAM) on the RGB frame.

        When `detection_payload` is provided (e.g., from `yolo_obj_slam.py`), it is parsed
        as JSON to create `Detection2D` instances; otherwise a mock inference is executed.
        """

        if detection_payload:
            try:
                data = json.loads(detection_payload)
                detections_json = data.get("detections", data)
            except json.JSONDecodeError:
                detections_json = []
        else:
            detections_json = []

        detections: List[Detection2D] = []
        for det in detections_json:
            bbox = det.get("bbox_xyxy") or det.get("box")
            if bbox is None:
                continue

            if isinstance(bbox, dict):
                bbox_tuple = (
                    int(bbox.get("x1", 0)),
                    int(bbox.get("y1", 0)),
                    int(bbox.get("x2", 0)),
                    int(bbox.get("y2", 0)),
                )
            else:
                x1, y1, x2, y2 = bbox
                bbox_tuple = (int(x1), int(y1), int(x2), int(y2))

            detections.append(
                Detection2D(
                    label=str(det.get("name") or det.get("label", "object")),
                    confidence=float(det.get("confidence", 0.5)),
                    bbox=bbox_tuple,
                )
            )

        if detections:
            return detections

        # --- Mock inference fall-back (simulating YOLO/SAM) ---
        h, w, _ = rgb_frame.shape
        synthetic = [
            Detection2D("chair", 0.92, (int(0.1 * w), int(0.4 * h), int(0.35 * w), int(0.9 * h))),
            Detection2D("monitor", 0.88, (int(0.5 * w), int(0.2 * h), int(0.8 * w), int(0.6 * h))),
        ]
        return synthetic

    def build_semantic_map_step(
        self,
        rgb_frame: np.ndarray,
        depth_frame: np.ndarray,
        pose: Optional[Tuple[float, float, float]] = None,
        detection_payload: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Fuse AI detections with depth to label the RTAB-Map point cloud."""

        detections = self._semantic_segmentation(rgb_frame, detection_payload)
        if not detections:
            summary = {
                "timestamp": time.time(),
                "detected_objects": 0,
                "labeled_points": 0,
                "pose": pose,
            }
            self.latest_summary = summary
            return summary

        labeled_points_total = 0
        segments = []
        for detection in detections:
            segment = self._project_2d_to_3d(rgb_frame, depth_frame, detection)
            labeled_points_total += len(segment.points)
            segments.append((detection, segment))
            total_points = self.mapper.add_segment(segment)
            print(
                f"[SemanticMapping] Labeled {len(segment.points)} points as '{detection.label}'. "
                f"Global map now holds {total_points} points."
            )

        summary = {
            "timestamp": time.time(),
            "detected_objects": len(detections),
            "labeled_points": labeled_points_total,
            "pose": pose,
            "labels": [d.label for d, _ in segments],
        }
        self.latest_summary = summary
        return summary

    # ------------------------------------------------------------------
    # --- Helpers ------------------------------------------------------
    # ------------------------------------------------------------------
    def update_camera_parameters(self, camera_info: Dict[str, float]) -> None:
        self.camera_params.update(camera_info)

    def _project_2d_to_3d(self, rgb_frame: np.ndarray, depth_frame: np.ndarray, detection: Detection2D) -> o3d.geometry.PointCloud:
        x_min, y_min, x_max, y_max = detection.bbox
        h, w = depth_frame.shape
        x_min = max(0, min(w - 1, x_min))
        y_min = max(0, min(h - 1, y_min))
        x_max = max(0, min(w - 1, x_max))
        y_max = max(0, min(h - 1, y_max))

        region_depth = depth_frame[y_min:y_max, x_min:x_max].astype(np.float32)
        if region_depth.size == 0:
            region_depth = np.ones((5, 5), dtype=np.float32) * 1500.0  # 1.5 m fallback

        fx = self.camera_params.get("fx", 600.0)
        fy = self.camera_params.get("fy", 600.0)
        cx = self.camera_params.get("cx", w / 2.0)
        cy = self.camera_params.get("cy", h / 2.0)
        depth_scale = self.camera_params.get("scale", 1000.0)

        step = max(1, region_depth.shape[0] // 32)
        ys, xs = np.mgrid[y_min:y_max:step, x_min:x_max:step]
        sampled_depth = depth_frame[ys, xs].astype(np.float32)
        sampled_depth[sampled_depth == 0] = 1500.0  # Assume 1.5 m when depth missing
        zs = sampled_depth / depth_scale
        xs = (xs - cx) * zs / fx
        ys = (ys - cy) * zs / fy

        points = np.stack((xs, ys, zs), axis=-1).reshape(-1, 3)
        colors = np.zeros_like(points)
        colors[:, :] = np.array([0.2, 0.8, 0.2])  # Green highlight for semantic object

        segment = o3d.geometry.PointCloud()
        segment.points = o3d.utility.Vector3dVector(points)
        segment.colors = o3d.utility.Vector3dVector(colors)
        return segment

    def get_current_map(self) -> o3d.geometry.PointCloud:
        return self.mapper.map


class SemanticMappingNode(Node):  # pragma: no cover - ROS runtime behaviour
    """ROS 2 node bridging the semantic pipeline with RealSense + RTAB-Map topics."""

    def __init__(self, config: SemanticMapConfig) -> None:
        super().__init__("semantic_mapping")
        self.config = config
        self.bridge = CvBridge()
        if CvBridge is None:
            raise ImportError(
                "cv_bridge is required for SemanticMappingNode. Install the ROS2 package "
                "`ros-humble-cv-bridge` (or matching distro)."
            )

        self.pipeline = SemanticMappingPipeline(config.classes)
        self._rgb_frame: Optional[Image] = None
        self._depth_frame: Optional[Image] = None
        self._latest_detections: Optional[str] = None
        self._camera_info_received = False
        self._lock = threading.Lock()

        # Subscribers mirroring `launch_slam_rtmap.py`
        self.create_subscription(Image, config.rgb_topic, self._on_rgb, 10)
        self.create_subscription(Image, config.depth_topic, self._on_depth, 10)
        self.create_subscription(CameraInfo, config.camera_info_topic, self._on_camera_info, 10)
        self.create_subscription(String, config.detection_topic, self._on_detections, 10)

        self._status_pub = self.create_publisher(String, config.status_topic, 10)

        self.get_logger().info(
            f"Semantic mapping node ready. Listening to RGB='{config.rgb_topic}', "
            f"Depth='{config.depth_topic}', Detections='{config.detection_topic}'."
        )

    # ------------------------------------------------------------------
    # ROS callbacks
    # ------------------------------------------------------------------
    def _on_camera_info(self, msg: CameraInfo) -> None:
        params = {
            "fx": msg.k[0],
            "fy": msg.k[4],
            "cx": msg.k[2],
            "cy": msg.k[5],
        }
        self.pipeline.update_camera_parameters(params)
        self._camera_info_received = True

    def _on_detections(self, msg: String) -> None:
        self._latest_detections = msg.data

    def _on_rgb(self, msg: Image) -> None:
        with self._lock:
            self._rgb_frame = msg
        self._try_process()

    def _on_depth(self, msg: Image) -> None:
        with self._lock:
            self._depth_frame = msg
        self._try_process()

    def _try_process(self) -> None:
        with self._lock:
            if not (self._rgb_frame and self._depth_frame and self._camera_info_received):
                return

            rgb_msg = self._rgb_frame
            depth_msg = self._depth_frame
            detections = self._latest_detections
            self._rgb_frame = None
            self._depth_frame = None

        try:
            rgb = self.bridge.imgmsg_to_cv2(rgb_msg, desired_encoding="bgr8")
            depth = self.bridge.imgmsg_to_cv2(depth_msg, desired_encoding="passthrough")
        except Exception as exc:
            self.get_logger().error(f"Failed to convert ROS images: {exc}")
            return

        summary = self.pipeline.build_semantic_map_step(rgb, depth, pose=None, detection_payload=detections)

        if self.config.publish_visualisation and cv2 is not None:
            self._show_overlay(rgb, summary)

        self._status_pub.publish(String(data=json.dumps(summary)))

    def _show_overlay(self, rgb_frame: np.ndarray, summary: Dict[str, Any]) -> None:
        if cv2 is None:
            return

        annotated = rgb_frame.copy()
        labels = summary.get("labels", [])
        text = f"Detections: {len(labels)} | Points labeled: {summary.get('labeled_points', 0)}"
        cv2.putText(
            annotated,
            text,
            (16, 32),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 0),
            2,
            cv2.LINE_AA,
        )
        cv2.imshow("Semantic Mapping", annotated)
        cv2.waitKey(1)


def main() -> None:  # pragma: no cover - runtime entry point
    if rclpy is None:
        raise ImportError(
            "rclpy is not available. Install the ROS 2 Python client libraries to run "
            "the semantic mapping node."
        ) from ROS_IMPORT_ERROR

    rclpy.init()
    config = SemanticMapConfig()
    node = SemanticMappingNode(config)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        node.get_logger().info("Shutting down Semantic Mapping node...")
    finally:
        node.destroy_node()
        if cv2 is not None and config.publish_visualisation:
            cv2.destroyAllWindows()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":  # pragma: no cover - allows standalone demo without ROS
    if rclpy is None:
        # Standalone simulation for quick testing without ROS.
        pipeline = SemanticMappingPipeline(classes=("chair", "monitor", "table"))
        mock_rgb = np.zeros((480, 640, 3), dtype=np.uint8)
        mock_depth = np.full((480, 640), 1500, dtype=np.uint16)
        summary = pipeline.build_semantic_map_step(mock_rgb, mock_depth)
        print("Standalone summary:", json.dumps(summary, indent=2))
        print(f"Labeled map contains {len(pipeline.get_current_map().points)} points.")
    else:
        main()
